spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mangas?createDatabaseIfNotExist=True
    username: root
    password: ''

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  driver-class-name: com.mysql.jdbc.Driver
